branches:
  only:
    - master
language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  pip: true
install:
  - python setup.py install
  - pip install codecov
script:
  - py.test --cov=roman_numerals -vv tests
after_success:
  - codecov
