branches:
  only:
    - master
language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  pip: true
install:
  - pip install -r requirements/check_requirements.txt
  - pip install -r requirements/test_requirements.txt
  - pip install -r requirements/development_requirements.txt
  - pip install codecov
script:
  - py.test --cov=roman_numerals -vv tests
after_success:
  - codecov
