branches:
  only:
    - master
language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  pip: true
install:
  - pip install six wheel setuptools  # for Travis Py3.4
  - find requirements -name '*.txt' | xargs -I {} pip install -r {}
  - pip install codecov
  - ./setup.py develop
script:
  - py.test --cov=roman_numerals -vv tests
after_success:
  - codecov
