branches:
  only:
    - master
language: python
python:
  - 3.4
  - 3.5
  - 3.6
cache:
  pip: true
install:
  - pip install six wheel setuptools  # for Travis Py3.4
  - find requirements -name '*.txt' | xargs -I {} pip install -r {}
  - pip install codecov pytest-travis-fold
  - ./setup.py develop
script:
  -  python setup.py check --strict --metadata --restructuredtext
  -  check-manifest .
  -  flake8 src tests setup.py
  -  isort --verbose --check-only --diff --recursive src tests setup.py
  -  mypy src tests
  -  pylint src tests setup.py
  - py.test --cov-report= --cov=\. -vv tests
after_success:
  - coverage combine --append && coverage report && coverage html && codecov
